### ISSUE TITLE
Create Roadmap so people can contribute

### ISSUE THREAD

**Issue by AhmedRiahi** [prsh9/KubeCtl-Dashboard#4]

**Comment by prsh9** [comment]
Will publish in a week's time

**Comment by prsh9** [comment]
Please feel free to contribute. Refer Contributing Guidelines. (Have updated the project structure.)
Roadmap is difficult to create as I only work on this in my free time, hence timelines can be hazy.
Planned things will be listed as issues so we know what to expect.
